# Generated by Django 6.1.1 on 2026-09-15 21:26

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models

def require_reconciled_legacy_database(apps,schema_editor):
    # The old implementation counted unpaid holds as sales and had no settlement flow.
    # Inferring which historical rows were actually paid would risk charging/refunding twice.
    if apps.get_model("bookings","Booking").objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError("Legacy bookings require a reviewed data migration before this upgrade. Restore the pre-upgrade backup and follow docs/DEPLOYMENT.md (Existing databases). Do not delete bookings or fake this migration.")

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_total_amount_and_more'),
        ('events', '0003_eventreview_savedevent_tickettype_quantity_reserved_and_more'),
        ('hotels', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('tourism', '0002_tourdeparture'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(require_reconciled_legacy_database,migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='bookingitem',
            name='unique_ticket_type_per_booking',
        ),
        migrations.RemoveIndex(
            model_name='bookingitem',
            name='bookings_bo_booking_3a1650_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookingitem',
            name='bookings_bo_ticket__f64557_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='fulfillment_status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('READY', 'Ready'), ('IN_PROGRESS', 'In_Progress'), ('COMPLETED', 'Completed')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='kind',
            field=models.CharField(choices=[('EVENT', 'Event'), ('HOTEL', 'Hotel'), ('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('TOURISM', 'Tourism')], default='EVENT', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='parent_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='request_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='transport.departure'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='restaurants.menuitem'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='room_night',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='hotels.roomnight'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='tour_departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='tourism.tourdeparture'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='events.tickettype'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_booking_request'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='booking_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.UniqueConstraint(fields=('booking', 'ticket_type'), name='booking_unique_ticket_type'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.UniqueConstraint(fields=('booking', 'room_night'), name='booking_unique_room_night'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.UniqueConstraint(fields=('booking', 'menu_item'), name='booking_unique_menu_item'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.UniqueConstraint(fields=('booking', 'departure'), name='booking_unique_departure'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.UniqueConstraint(fields=('booking', 'tour_departure'), name='booking_unique_tour_departure'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('subtotal__gte', 0), ('unit_price__gte', 0)), name='booking_item_positive'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal', django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')))), name='booking_item_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('departure__isnull', True), ('menu_item__isnull', True), ('room_night__isnull', True), ('ticket_type__isnull', False), ('tour_departure__isnull', True)), models.Q(('departure__isnull', True), ('menu_item__isnull', True), ('room_night__isnull', False), ('ticket_type__isnull', True), ('tour_departure__isnull', True)), models.Q(('departure__isnull', True), ('menu_item__isnull', False), ('room_night__isnull', True), ('ticket_type__isnull', True), ('tour_departure__isnull', True)), models.Q(('departure__isnull', False), ('menu_item__isnull', True), ('room_night__isnull', True), ('ticket_type__isnull', True), ('tour_departure__isnull', True)), models.Q(('departure__isnull', True), ('menu_item__isnull', True), ('room_night__isnull', True), ('ticket_type__isnull', True), ('tour_departure__isnull', False)), _connector='OR'), name='booking_item_one_source'),
        ),
    ]
