# Generated by Django 6.1.1 on 2026-09-16 07:24

import django.db.models.expressions
import django.db.models.functions.math
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_and_more'),
        ('events', '0003_eventreview_savedevent_tickettype_quantity_reserved_and_more'),
        ('hotels', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('tourism', '0002_tourdeparture'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingitem',
            name='booking_item_subtotal',
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal', django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')), 2))), name='booking_item_subtotal'),
        ),
    ]
