# Generated by Django 6.1.1 on 2026-09-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_bookingitem_booking_item_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
