# Generated by Django 6.1.1 on 2026-09-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(db_index=True, default='General', max_length=100),
            preserve_default=False,
        ),
    ]
