# Generated by Django 6.1.1 on 2026-09-27 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cancel_old_verification_links(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    Notification.objects.using(schema_editor.connection.alias).filter(
        key__startswith='verify:', sent_at__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(cancel_old_verification_links, migrations.RunPython.noop),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
