# Generated by Django 6.1.1 on 2026-10-06 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_import_existing_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='community.article')),
            ],
        ),
    ]
