# Generated by Django 6.1.1 on 2026-09-28 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_completed_at'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'permissions': [('reply_support', 'Receive and reply to support conversations')]},
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='direct_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='provider_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image_data',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bookings.booking'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'sender', 'client_id'), name='message_send_once'),
        ),
        migrations.AddField(
            model_name='chatblock',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatblock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatblock',
            constraint=models.UniqueConstraint(fields=('user', 'blocked'), name='chat_block_once'),
        ),
    ]
