# Generated by Django 6.1.1 on 2026-09-15 21:26

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDeparture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='tourism.tourpackage')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='tourism_tourdeparture_price'), models.CheckConstraint(condition=models.Q(('quantity__gte', django.db.models.expressions.CombinedExpression(models.F('quantity_reserved'), '+', models.F('quantity_sold')))), name='tourism_tourdeparture_stock'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='tour_departure_dates')],
            },
        ),
    ]
