# Generated by Django 6.1.1 on 2026-09-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventreview_savedevent_tickettype_quantity_reserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
