# Generated by Django 6.1.1 on 2026-09-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_is_suspended_event_review_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='membership_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='membership_early_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='minimum_plan',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('diamond', 'Diamond')], default='bronze', max_length=10),
        ),
    ]
