# Generated by Django 6.1.1 on 2026-10-09 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_majoreventpromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorEventAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promotion_updated_at', models.DateTimeField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('destination_url', models.URLField(max_length=1000)),
                ('image_path', models.CharField(blank=True, max_length=1000)),
                ('last_user_id', models.PositiveBigIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
        ),
    ]
