import SiteImage from '@/components/SiteImage';
import { useState } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { Users, Megaphone, ChartNoAxesCombined, ShieldCheck } from 'lucide-react';
import Header from '@/components/layout/Header';
import { useAuth } from '@/components/context/AuthContext';
import { useApi } from '@/hooks/useApi';
import { api } from '@/lib/api';
import VerificationScreen from '@/components/auth/VerificationScreen';
import { TermsContent } from './Terms';
import SignUpSocialButtons from '@/components/auth/register/SignUpSocialButtons';
import { PASSWORD_HELP, passwordError } from '@/lib/passwordPolicy';
import PasswordStrength from '@/components/auth/PasswordStrength';

const input='mt-2 w-full rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-green-700';
function OrganizerShell({children}) {return <div className="min-h-screen bg-white"><Header/><main className="mx-auto grid max-w-7xl gap-12 px-6 py-12 lg:grid-cols-2"><aside className="relative overflow-hidden"><h1 className="text-3xl font-bold leading-tight sm:text-4xl">Join the Community<br/>of <span className="text-[#00651b]">Amazing Organizers</span></h1><p className="mt-5">Create, manage and promote events<br/>that impact lives.</p><ul className="relative z-10 mt-8 space-y-5">{[[Users,'Reach more audiences'],[Megaphone,'Boost your brand'],[ChartNoAxesCombined,'Easy event management'],[ShieldCheck,'Secure payouts']].map(([Icon,text])=><li key={text} className="flex items-center gap-3 font-semibold"><span className="rounded-full bg-emerald-700 p-2 text-white"><Icon size={18}/></span>{text}</li>)}</ul><SiteImage src="/design/organizer-signup.png" alt="Organizers collaborating around a laptop" className="mt-6 w-full object-contain"/></aside><section className="mx-auto w-full max-w-xl">{children}</section></main></div>;}
export function OrganizerSignup() {
  const {user,login}=useAuth();const navigate=useNavigate();
  const [pending,setPending]=useState(null);const [business,setBusiness]=useState('');const [busy,setBusy]=useState(false);const [termsAccepted,setTermsAccepted]=useState(false);const [passwordValue,setPasswordValue]=useState('');
  if(user)return <Navigate to="/organizer/apply" replace/>;
  const submit=async event=>{event.preventDefault();if(busy)return;setBusy(true);const form=new FormData(event.currentTarget);const [first_name,...last]=form.get('fullName').trim().split(/\s+/);const details={first_name,last_name:last.join(' '),username:form.get('username').trim(),email:form.get('email').trim().toLowerCase(),phone:form.get('phone').trim(),password:form.get('password')};try{const error=passwordError(details.password);if(error)throw new Error(error);await api('/auth/resend-verification/',{method:'POST',body:{email:details.email}});setBusiness(form.get('business_name').trim());setPending(details);}catch(error){toast.error(error.message);}finally{setBusy(false);}};
  const verify=async otp_code=>{await api('/auth/register/',{method:'POST',body:{...pending,otp_code}});const credentials={email:pending.email,password:pending.password};try{await login(credentials);navigate('/organizer/apply',{state:{business_name:business}});}catch{toast('Your email is verified and your account is ready. Log in to continue.');navigate('/organizer/login');}finally{setPending(null);}};
  if(pending)return <VerificationScreen email={pending.email} onVerify={verify} onResend={()=>api('/auth/resend-verification/',{method:'POST',body:{email:pending.email}})} onBack={()=>setPending(null)} submitLabel="Verify and create account"/>;
  return <OrganizerShell><h2 className="text-center text-3xl font-bold">Create Organizer Account</h2><p className="mt-3 text-center text-slate-500">Let’s get you started.</p><form onSubmit={submit} className="mt-10 space-y-5"><div className="grid gap-5 sm:grid-cols-2">{[['fullName','Full Name','text'],['username','Username','text'],['business_name','Business / Organisation Name','text'],['phone','Phone Number','tel']].map(([name,label,type])=><label key={name} className="text-sm font-medium">{label}<input required name={name} type={type} minLength={name==='phone'?10:2} maxLength={name==='username'?150:name==='phone'?20:200} pattern={
  name === 'username'
    ? '[A-Za-z0-9_@.+\\-]+'
    : name === 'phone'
      ? '[+0-9 ()\\-]+'
      : undefined
} className={input}/></label>)}</div><label className="block text-sm font-medium">Email Address<input name="email" type="email" autoComplete="email" required className={input}/></label><label className="block text-sm font-medium">Password<input name="password" type="password" autoComplete="new-password" required minLength={8} maxLength={128} onChange={event=>setPasswordValue(event.target.value)} className={input}/><PasswordStrength password={passwordValue}/><span className="mt-1 block text-xs font-normal text-slate-500">{PASSWORD_HELP}</span></label><label className="flex gap-2 text-sm"><input type="checkbox" required checked={termsAccepted} onChange={event=>setTermsAccepted(event.target.checked)}/>I agree to the <Link to="/terms" className="font-semibold text-green-800">Terms & Conditions</Link></label><button disabled={busy} className="w-full rounded-lg bg-[#ff6500] py-3 font-semibold text-white disabled:opacity-50">{busy?'Sending code…':'Sign Up'}</button></form><p className="my-5 text-center text-sm text-slate-400">Or continue with</p><SignUpSocialButtons termsAccepted={termsAccepted}/><p className="mt-6 text-center text-sm text-slate-500">Already have an account? <Link to="/organizer/login" className="text-green-800">Log In</Link></p></OrganizerShell>;
}
export default function OrganizerApplication() {
  const {user,loading,reloadUser}=useAuth();const location=useLocation();
  const application=useApi(user?'/auth/organizer-application/':null);
  const [details,setDetails]=useState(null);const [busy,setBusy]=useState(false);const [editing,setEditing]=useState(false);
  if(loading)return <p role="status" className="p-8">Loading…</p>;
  if(!user)return <Navigate to="/organizer/signup" replace/>;
  if(user.is_verified&&user.role==='ORGANIZER')return <Navigate to="/organizer/dashboard" replace/>;
  const submit=async()=>{if(busy)return;setBusy(true);try{await api('/auth/organizer-application/',{method:'POST',body:{...details,accept_terms:true}});setDetails(null);setEditing(false);await reloadUser();application.reload();toast.success('Your application has been submitted for review.');}catch(error){toast.error(error.message);}finally{setBusy(false);}};
  const profile=application.data;
  return <OrganizerShell><h2 className="text-3xl font-bold">Want To Host An Event?</h2><p className="mt-3 text-slate-500">Let’s get you started.</p>{application.loading?<p role="status" className="mt-8">Loading your application…</p>:application.error?<div role="alert" className="mt-8">{application.error.message}<button onClick={application.reload} className="ml-3 underline">Retry</button></div>:profile&&!editing&&!details?<div className="mt-8 rounded-xl border border-green-100 bg-green-50 p-6"><h3 className="font-bold">Application {profile.status.replaceAll('_',' ').toLowerCase()}</h3><p className="mt-3 text-sm">{profile.status==='PENDING'?'Your application is awaiting review. We will notify you when a decision is made.':profile.review_note||'Review your application details before resubmitting.'}</p>{['REJECTED','NEEDS_INFO'].includes(profile.status)&&<button onClick={()=>setEditing(true)} className="mt-5 rounded-lg bg-green-800 px-5 py-3 text-white">Update application</button>}<Link to="/dashboard" className="mt-5 block text-sm text-green-800">Go to my dashboard</Link></div>:details?<div className="mt-8 space-y-5"><h3 className="text-xl font-bold">Organizer Terms & Conditions</h3><TermsContent/><Link to="/terms" className="block text-sm text-green-800 underline">Read the platform terms</Link><button disabled={busy} onClick={submit} className="w-full rounded-lg bg-[#ff6500] py-3 font-semibold text-white disabled:opacity-50">{busy?'Submitting…':'Accept and Submit Application'}</button><button disabled={busy} onClick={()=>setDetails(null)} className="text-sm text-green-800">← Edit details</button></div>:<form key={editing?'edit':'new'} onSubmit={event=>{event.preventDefault();setDetails(Object.fromEntries(new FormData(event.currentTarget)));}} className="mt-10 space-y-6">{[['business_name','Business / Organisation Name',profile?.business_name||location.state?.business_name||''],['event_type','Type of Event',profile?.event_type||''],['coverage_region','Region of Event Coverage',profile?.coverage_region||''],['contact_phone','Contact Phone',profile?.contact_phone||user.phone||'']].map(([name,label,value])=><label key={name} className="block text-sm font-medium">{label}<input required name={name} defaultValue={value} maxLength={name==='contact_phone'?20:100} type={name==='contact_phone'?'tel':'text'} className={input}/></label>)}<label className="block text-sm font-medium">Verification reference (optional)<input name="verification_reference" defaultValue={profile?.verification_reference||''} maxLength={200} className={input}/></label><label className="block text-sm font-medium">Business description (optional)<textarea name="description" defaultValue={profile?.description||''} rows={3} maxLength={2000} className={input}/></label><button className="w-full rounded-lg bg-[#ff6500] py-3 font-semibold text-white">Terms & Conditions →</button></form>}</OrganizerShell>;
}
