# Generated by Django 6.1.1 on 2026-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationcode_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='coverage_region',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='event_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='review_note',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='terms_version',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='session_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_INFO', 'Needs Info')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='verification_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
