# Generated by Django 6.1.1 on 2026-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_socialidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major_event_popup_pending',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
