# Generated by Django 6.1.1 on 2026-10-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_major_event_popup_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='major_event_popup_pending',
        ),
    ]
