# Generated by Django 6.1.1 on 2026-09-15 21:26

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('address', models.TextField()),
                ('amenities', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_types', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomNight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nights', to='hotels.roomtype')),
            ],
            options={
                'ordering': ['date', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(condition=models.Q(('max_guests__gte', 1)), name='room_guests_positive'),
        ),
        migrations.AddConstraint(
            model_name='roomnight',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='hotels_roomnight_price'),
        ),
        migrations.AddConstraint(
            model_name='roomnight',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', django.db.models.expressions.CombinedExpression(models.F('quantity_reserved'), '+', models.F('quantity_sold')))), name='hotels_roomnight_stock'),
        ),
        migrations.AddConstraint(
            model_name='roomnight',
            constraint=models.UniqueConstraint(fields=('room_type', 'date'), name='unique_room_night'),
        ),
    ]
