# Generated by Django 6.1.1 on 2026-09-13 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('STRIPE', 'Stripe')], max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='payments_pa_booking_57d6de_idx'), models.Index(fields=['user', 'created_at'], name='payments_pa_user_id_5bbfc5_idx'), models.Index(fields=['provider', 'status'], name='payments_pa_provide_cc7861_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_reference'), name='unique_provider_reference')],
            },
        ),
    ]
