# Generated by Django 6.1.1 on 2026-09-16 17:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_ledgerentry_paymentevent_refund_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_code', models.CharField(max_length=100)),
                ('recipient_id', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('account_last4', models.CharField(max_length=4)),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'permissions': [('review_payoutaccount', 'Review provider bank accounts')],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('OTP_REQUIRED', 'Otp Required'), ('UNKNOWN', 'Unknown'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('REVIEW', 'Review'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=20)),
                ('approved_at', models.DateTimeField(null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_approvals', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payoutaccount')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'permissions': [('release_payout', 'Approve, finalize and reconcile provider payouts')],
            },
        ),
        migrations.CreateModel(
            name='PayoutAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('transfer_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_at', models.DateTimeField(db_index=True, null=True)),
                ('finalized_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='payments.payout')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='payments.payout')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_items', to='payments.ledgerentry')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payoutaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('provider',), name='one_current_payout_account'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(fields=('provider', 'idempotency_key'), name='payout_request_key'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_positive'),
        ),
        migrations.AddConstraint(
            model_name='payoutitem',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('sale',), name='sale_paid_out_once'),
        ),
        migrations.AddConstraint(
            model_name='payoutitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_item_positive'),
        ),
    ]
