# Generated by Django 6.1.1 on 2026-09-13 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('qr_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='ACTIVE', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='bookings.booking')),
                ('booking_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='bookings.bookingitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.tickettype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='tickets_tic_booking_0c9f17_idx'), models.Index(fields=['owner', 'status'], name='tickets_tic_owner_i_70fd59_idx'), models.Index(fields=['ticket_type', 'status'], name='tickets_tic_ticket__0ca21b_idx')],
            },
        ),
    ]
