# Generated by Django 6.1.1 on 2026-09-15 21:26

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(db_index=True, max_length=200)),
                ('destination', models.CharField(db_index=True, max_length=200)),
                ('pickup_address', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('departs_at', models.DateTimeField(db_index=True)),
                ('arrives_at', models.DateTimeField()),
                ('vehicle', models.CharField(max_length=100)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='transport.route')),
            ],
            options={
                'ordering': ['departs_at', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='transport_departure_price'), models.CheckConstraint(condition=models.Q(('quantity__gte', django.db.models.expressions.CombinedExpression(models.F('quantity_reserved'), '+', models.F('quantity_sold')))), name='transport_departure_stock'), models.CheckConstraint(condition=models.Q(('arrives_at__gt', models.F('departs_at'))), name='departure_dates_valid')],
            },
        ),
    ]
